---

language: java
services:
- mysql

notifications:
  email:
    recipients:
    - podnov@gmail.com
    on_success: change
    on_failure: always

install: skip

before_script:
- mysql -u root -e "create database queryinfo_test default character set utf8 default collate utf8_general_ci;"
- mysql -u root -e "create user 'queryinfo_test'@'localhost' IDENTIFIED BY 'queryinfo_test';"
- mysql -u root -e "grant all privileges on *.* to 'queryinfo_test'@'localhost';"

script: mvn verify -Ptravis
